main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from .views import all_products, products_filter, saveorder
from django.urls import path

app_name = 'shop'

urlpatterns = [
    path("all_p", all_products, name = 'all_products'),
    path("products_filter/<int:category_id>", products_filter, name = 'products_filter'),
    path("saveorder", saveorder, name='saveorder')
]

shop/models.py
from django.db import models
from django.db.models.fields import CharField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='категория')

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
    
    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name = models.CharField(max_length=20, verbose_name="название")
    description = models.TextField(max_length=200, verbose_name = 'описание', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images', blank=False)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def __str__(self):
        return f'{self.name}'


class Cart(models.Model):
    owner = models.CharField(max_length=50)
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=100, decimal_places=2)

    class Meta:
        verbose_name = 'корзина'
        verbose_name_plural = 'корзины'

    def __str__(self):
        return f'{self.owner} - {self.total_price}'

shop/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model
from .models import Product, Category, Cart

User = get_user_model()

def navbar_data():
    categories = Category.objects.all()
    return {"categories":categories}

def all_products(request):
    burgers = Product.objects.filter(category_id=1)
    drinks = Product.objects.filter(category_id=2)
    return render(request, 'all_products.html', {'burgers':burgers, 'drinks':drinks, 'navbar':navbar_data()})

def products_filter(request, category_id):
    products = Product.objects.filter(category = category_id)
    return render(request, 'products_filter.html', {'products':products, 'navbar':navbar_data()})

def saveorder(request): 
    owner = 'henry'
    products = Product.objects.get(id = request.POST['product_id'])
    if request.POST['count'] == False:
        request.POST['count'] = 0
        total_price = int(request.POST['count']) * int(float(products.price))
        cart = Cart.objects.create(
            owner=owner,
            total_price=total_price,
            products=products
        )
    cart.save()
    return redirect('shop:all_products')

shop/templates/all_products.html
{% extends 'index.html' %}
{% block content %}
<style>
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
      text-align: center;
      width: 20rem;
      background-color:rgb(255, 255, 255);
      margin-left: 10%; 
      margin-top: 5%;
      transition: background-color 0.5s linear;
    }
    .card-container {
        display: grid;
        padding: 1rem;
        grid-template-columns: repeat(3, minmax(320px, 1fr));
        grid-gap: 1rem; 
    }
    .card:hover {
            background-color: rgb(201, 175, 175);
          }
    
    </style>
<h1>Burgers</h1>
<form method='POST' action='saveorder'>
  {% csrf_token %}
<section class="card-container">
{% for product in burgers %}
<div class="card" style="width: 18rem;">
    <img src="{{product.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card_text">{{product.name}}</p>
      <p class="card-text">{{product.description}}</p>
      <p class="card-text">{{product.price}} сом</p>
    </div>
      количество <input type="number" name="count" \>
      <input type='hidden' value="{{product.id}}" name="product_id" >
  </div>
{% endfor %}
</section>


<h1>Drinks</h1>
<section class="card-container" action='saveorder'>
    {% for product in drinks %}
    <div class="card" style="width: 18rem;">
        <img src="{{product.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card_text">{{product.name}}</p>
          <p class="card-text">{{product.description}}</p>
          <p class="card-text">{{product.price}} сом</p>
        </div>
          количество <input type="number" name="count" \>
          <input type='hidden' value="{{product.id}}" name="product_id" >
      </div>
    {% endfor %}
    </section>
    <input type="submit" value="в корзину">
  </form>
{% endblock %}

shop/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">DSGS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'shop:all_products' %}">Home</a>
              </li>
              {% for category in navbar.categories %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:products_filter' category_id=category.id %}">{{category.name}}</a>
              </li>
              {% endfor %}
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
</header>
<body>
{% block content %}
{% endblock %}
</body>
</html>

shop/templates/products_filter.html
{% extends 'index.html' %}
{% block content %}
<style>
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 16px;
    text-align: center;
    width: 20rem;
    background-color:rgb(255, 255, 255);
    margin-left: 10%; 
    margin-top: 5%;
    transition: background-color 0.5s linear;
  }
  .card-container {
      display: grid;
      padding: 1rem;
      grid-template-columns: repeat(3, minmax(320px, 1fr));
      grid-gap: 1rem; 
  }
  .card:hover {
          background-color: rgb(201, 175, 175);
        }
  
  </style>
<section class="card-container">
{% for product in products %}
<div class="card" style="width: 18rem;">
  <img src="{{product.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card_text">{{product.name}}</p>
    <p class="card-text">{{product.description}}</p>
    <p class="card-text">{{product.price}} сом</p>
  </div>
</div>
{% endfor %}
</section>
{% endblock %}